# Use the official Node.js 14 image as a base
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy the entire project to the working directory
COPY . .

# Expose port 3000 for the Node.js production server
EXPOSE 3000

# Command to start the Node.js production server
CMD ["npm", "start"]
